name: Build and deploy documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Create website directory
        run: mkdir _site/
      - name: Build library documentation
        working-directory: ./lib
        run: cargo doc --no-deps --all-features
      - name: Copy library documentation
        run: cp -a ./lib/target/doc/ ./_site/crates
      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=crates/intel_crashlog">' > _site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.repository == 'intel/crashlog'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
